# Generated by Django 2.1.5 on 2019-03-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=100)),
                ('crop_description', models.CharField(max_length=254)),
                ('crop_image', models.ImageField(upload_to='crop_image')),
                ('location', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('now', models.DateTimeField(auto_now_add=True)),
                ('exp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('l_name', models.CharField(max_length=254)),
                ('mobile', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='efarm.CropCategory'),
        ),
    ]
