# Generated by Django 2.1 on 2019-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0002_auto_20190418_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=254)),
                ('cust_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('cust_msg', models.CharField(max_length=50)),
            ],
        ),
    ]
