# Generated by Django 2.1 on 2019-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cust_msg',
            field=models.TextField(max_length=254),
        ),
    ]
