# Generated by Django 2.1 on 2019-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0004_auto_20190423_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farmer_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
